"""init records table

Revision ID: 7af002d191b9
Revises: 
Create Date: 2023-03-11 20:29:58.074902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af002d191b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records')
    op.add_column('records', sa.Column("key", sa.String))
    op.add_column('records', sa.Column("value", sa.String))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('key', "value")
    op.drop_table('records')
    # ### end Alembic commands ###
